### ISSUE TITLE
Failed to parse response

### ISSUE THREAD

**Issue by vhscom** [SeoFernando25/ulauncher-gpt#6]
Attaching an image of an error I saw after I set up this plugin today using a new API key from OpenAI generated today. I'm seeing responses, but they appear to be plan related.

![IMG_20231104_140128_edit_66881565859064.jpg](https://github.com/seofernando25/ulauncher-gpt/assets/97140109/2479c4d9-d399-4dde-afde-0f86b2cc0c74)

**Comment by seofernando25** [comment]
Hi I'm sorry you're seeing this error. If you press "enter" I believe it will copy the error to your clipboard.

Would you mind pasting it? 
(Don't forget to remove sensitive info if any)

**Comment by vhscom** [comment]
Thank you for your help. 🙏 Pressing enter indeed copies the error to the clipboard. Message reads:

```term
You exceeded your current quota, please check your plan and billing details.
```

I typically use GPT-3.5 through the web interface at https://chat.openai.com/. I am not a paying customer.

**Comment by vhscom** [comment]
Based on some additional research it seems only new accounts benefit from free API requests. I haven't checked my plan but the error seems clear using the plugin will require a non-free account.

**Comment by ercling** [comment]
Hi,
I am a paid customer. I have the same error. I have tried different models: gpt-3.5-turbo, gpt-4, gpt-4-1106-preview

**Comment by vhscom** [comment]
> I am a paid customer. I have the same error.

Are you able to use your API key outside of Ulauncher? I suspect it's something related to your plan if you see the same error. Or possibly some kind of restricted use by OpenAPI.

LocalAI is a free alternative to ChatGPT for users on beefier hardware.

**Comment by vhscom** [comment]
> I am a paid customer. I have the same error.

Are you able to use your API key outside of Ulauncher? I suspect it's something related to your plan if you see the same error.

LocalAI is a free alternative to ChatGPT for users on beefier hardware.

**Comment by vhscom** [comment]
Closing in favor of LocalAI offline support.
